version: "3.8"

services:
  lancedb:
    build: ./lancedb
    container_name: lancedb
    volumes:
      - ./my_lancedb:/app/my_lancedb   # shared database
    restart: on-failure

  streamlit:
    build: ./streamlit
    container_name: lancedb_streamlit
    ports:
      - "8501:8501"     # Streamlit UI
    volumes:
      - ./my_lancedb:/app/my_lancedb   # same DB folder shared
    depends_on:
      - lancedb
    restart: unless-stopped

  vuri:
    build: ./vuri
    container_name: vuri
    ports:
      - "8502:8502"     # Streamlit UI
    volumes:
      - ./my_lancedb:/app/my_lancedb   # same DB folder shared
    depends_on:
      - lancedb
    restart: unless-stopped