FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt   # install only once if unchanged

COPY scripts/ /app/scripts/

CMD ["python3", "/app/scripts/create_table.py"]

